---

- name: Check for presence of Hashicorp Vault path variable
  assert:
    that:
      - hashicorp_vault_private_key_path is defined
    fail_msg: "Variable hashicorp_vault_private_key_path was not provided"
    success_msg: "Variable hashicorp_vault_private_key_path was provided"

- name: Retrieve SSH private key from Hashicorp Vault
  set_fact:
    ssh_key_json: "{{ lookup('community.hashi_vault.hashi_vault', hashicorp_vault_private_key_path)  }}"

- name: Ensure SSH directory exists
  file:
    path: "{{ ssh_dir_path }}"
    owner: "{{ ssh_dir_owner}}"
    group: "{{ ssh_dir_group }}"
    state: directory
    mode: '{{ ssh_dir_mode }}'
  when: ssh_dir_check

- name: Write SSH private key to Ansible controller
  copy:
    content: "{{ ssh_key_json['ssh_private_key'] | b64decode }}"
    dest: "{{ ssh_key_path }}"
    owner: "{{ ssh_key_owner  }}"
    group: "{{ ssh_key_group }}"
    mode: '{{ ssh_key_mode }}'
