---

- name: Check for presence of Hashicorp Vault path variable
  assert:
    that:
      - hashicorp_vault_private_key_path is defined
    fail_msg: "Variable hashicorp_vault_private_key_path was not provided"
    success_msg: "Variable hashicorp_vault_private_key_path was provided"

- name: Retrieve SSH private key from Hashicorp Vault
  set_fact:
    ssh_key_matter: "{{ lookup('community.hashi_vault.hashi_vault', hashicorp_vault_private_key_path)  }}"

- name: Ensure SSH directory exists
  file:
    path: "{{ ssh_dir_path }}"
    owner: "{{ ansible_controller_ssh_dir_owner}}"
    group: "{{ ansible_controller_ssh_dir_group }}"
    state: directory
    mode: '{{ ansible_controller_ssh_dir_mode }}'
  when: ansible_controller_ssh_dir_check

- name: Write SSH private key to Ansible controller
  copy:
    content: "{{ ssh_key_matter | b64decode }}"
    dest: "{{ ssh_key_path }}"
    owner: "{{ ansible_controller_ssh_dir_owner}}"
    group: "{{ ansible_controller_ssh_dir_group }}"
    mode: '{{ ansible_controller_ssh_key_mode }}'
