---

- name: Check for valid mode of operation
  assert:
    that:
      - ssh_key_action == "install" or ssh_key_action == "remove"
    msg: "Unsupported value provided for 'ssh_key_action'; specify either 'install' or 'remove'"

- set_fact:
    ssh_dir_prefix: "{{ '/home' if ssh_dir_owner != 'root' }}"

- set_fact:
    ssh_dir_path: "{{ ssh_dir_prefix }}/{{ ssh_dir_owner }}/.ssh"

- set_fact:
    ssh_key_path: "{{ ssh_dir_path }}/{{ ssh_key_name }}"

- include_tasks: create.yml
  when: ssh_key_action == "install"

- include_tasks: remove.yml
  when: ssh_key_action == "remove"
