---

- set_fact:
    ssh_dir_prefix: "{{ '/home' if ssh_dir_owner != 'root' }}"

- set_fact:
    ssh_dir_path: "{{ ssh_dir_prefix }}/{{ ssh_dir_owner }}/.ssh"

- set_fact:
    ssh_key_path: "{{ ssh_dir_path }}/{{ ssh_key_name }}"

- include_tasks: create.yml
  when: ssh_key_install

- include_tasks: remove.yml
  when: not ssh_key_install
